### PR TITLE
Mrtnster

### PR DESCRIPTION
**Pull request by ghost**
**rwrootfs**: by using arch-chroot script it is possible to install/upgrade/remove packages in the chroot environment
**overlayrooot.install**: call of mkinitcpio is not needed as there is a trigger hook in the kernel package which automatically runs mkinitcpio if a file was installed/upgraded in /usr/lib/initcpio/*
**PKGBUILD**: added arch-install-scripts as optional dependency (which contains the arch-choroot script)

### CODE REVIEW

**Comment by nils-werner** [comment]
Nice, thanks for your contribution!

One question: Why did you remove `mkinitcpio -p linux-raspberrypi` in [`post_upgrade()`](https://github.com/nils-werner/raspi-overlayroot/pull/5/files#diff-d2352ce5acc4650551fc7f6a9515cfeaL11) but not in [`post_install()`](https://github.com/mrtnster/raspi-overlayroot/blob/master/overlayroot.install#L2)?

**Comment by ghost** [comment]
Oh, it was just a mistake.

**Comment by nils-werner** [comment]
Ah, OK.

And what about changing `HOOKS` or uninstalling files in `/usr/lib/initcpio/`? Does the user have to re-run `mkinitcpio` then?

**Comment by ghost** [comment]
Looking at the `/usr/share/libalpm/hooks/99-linux.hook` it doesen't generate a new initrd when a package is removed. I think it isn't a problem as all the files needed by the hook are still in the current initrd. However at the next run of mkinitcpio it will complain that a hook is missing, but won't fail.

So a reminder to remove `overlayroot` from `HOOKS` is good enough at the uninstallation.

When files are installed or upgraded in `/usr/lib/initcpio/*` (by running `pacman`), the transaction will trigger the linux kernel package's hook (`99-linux.hook`) and a new initrd will be generated.

When the `mkinitcpio.conf` is changed by the user, it will take effect at the next run of mkinitcpio. So in this case the user should run `mkinitcpio` manually.

**Comment by nils-werner** [comment]
OK, the way I understand it is:

 - Do not run `mkinitcpio` anywhere in `.install`
 - In `post_remove`: grep `/etc/mkinitcpio.conf` for `overlayroot` and if present, show message about removing it from `HOOKS` and re-running `mkinitcpio`
 - Mention calling `mkinitcpio` after editing `HOOKS` in `README.md`

what do you think?

**Comment by nils-werner** [comment]
Also, I would like to replace all instances of

    mkinitcpio -p linux-raspberrypi

with

    mkinitcpio -P

(`-P` stands for `--allpresets`)

**Comment by ghost** [comment]
I think these changes are OK.

**Comment by mrtnster** [comment]
I think these changes are OK.

**Comment by nils-werner** [comment]
I have updated the code and incorporated your idea of using `arch-chroot`. Thanks!

**Pull request closed without merging**
